
'use client'
import {useEffect,useRef,useState} from 'react'; import {PublicNav} from '@/components/public-nav'
type Area='Front'|'Back'|'Left Sleeve'|'Right Sleeve'|'Hood'|'Pocket'
export default function Studio(){
 const [product,setProduct]=useState('T-Shirt');const [area,setArea]=useState<Area>('Front');const [image,setImage]=useState<string>('');const [low,setLow]=useState(false);const [requestEnhancement,setRequestEnhancement]=useState(false);const [isEnhancedPreview,setIsEnhancedPreview]=useState(false);const [text,setText]=useState('');const [saved,setSaved]=useState(false);const file=useRef<HTMLInputElement>(null)
 useEffect(()=>{const d=localStorage.getItem('ct-draft');if(d){try{const x=JSON.parse(d);setProduct(x.product||'T-Shirt');setText(x.text||'');setImage(x.image||'')}catch{}}},[])
 useEffect(()=>{const t=setTimeout(()=>{localStorage.setItem('ct-draft',JSON.stringify({product,area,text,image,requestEnhancement}));setSaved(true);setTimeout(()=>setSaved(false),900)},600);return()=>clearTimeout(t)},[product,area,text,image,requestEnhancement])
 function upload(f?:File){if(!f)return;const u=URL.createObjectURL(f);setImage(u);setRequestEnhancement(false);setIsEnhancedPreview(false);const im=new Image();im.onload=()=>setLow(im.naturalWidth<900||im.naturalHeight<900);im.src=u}
 const areas:Area[]=product==='Hoodie'?['Front','Back','Left Sleeve','Right Sleeve','Hood','Pocket']:['Front','Back','Left Sleeve','Right Sleeve','Pocket']
 return <div className="shell"><PublicNav/><main className="container section"><div className="top"><div><h1 style={{fontSize:48,letterSpacing:-2,margin:0}}>Design Studio</h1><p className="muted">Choose product → create design → review and checkout</p></div><span className="badge">{saved?'Saved':'Auto-save on'}</span></div><div className="designer"><aside className="toolbox"><h3>Product</h3><select value={product} onChange={e=>setProduct(e.target.value)}><option>T-Shirt</option><option>Hoodie</option><option>Bring Your Own</option></select><h3>Print area</h3><div className="tabs">{areas.map(a=><button key={a} className={'tab '+(area===a?'active':'')} onClick={()=>setArea(a)}>{a}</button>)}</div><h3>Image</h3><input ref={file} type="file" accept="image/*" hidden onChange={e=>upload(e.target.files?.[0])}/><button className="secondary" onClick={()=>file.current?.click()}>Upload Image</button><p className="muted">Maximum 5 images. Image print limit: 11&quot; × 17&quot;.</p><h3>Text</h3><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Add your text"/><p className="muted">Maximum 15 text items. Text limit: 11.50&quot; × 17&quot;.</p>{low&&<div className="warning"><b>Low image quality detected.</b><br/>This image may print blurry. If this is the only image you have, our team will do our best to improve it before printing.<label style={{display:'flex',gap:8,alignItems:'flex-start',marginTop:12}}><input type="checkbox" checked={requestEnhancement} onChange={e=>setRequestEnhancement(e.target.checked)}/><span><b>Request image enhancement</b><br/><small>Our team will review the image. Improvement is not guaranteed when the original file is very small.</small></span></label><div className="row" style={{marginTop:10}}><button className="secondary" onClick={()=>file.current?.click()}>Upload Better Image</button><button className="secondary" onClick={()=>setLow(false)}>Continue Anyway</button></div></div>}</aside><section className="canvas"><div className="printarea">{image&&<img src={image} alt="Uploaded design" className="designobj" style={{objectFit:'contain',background:'transparent'}}/>}{text&&<div className="designobj" style={{top:245,background:'transparent',border:'none'}}>{text}</div>}{isEnhancedPreview&&<div className="watermark">CUSTOM TEEZ • ENHANCED PREVIEW</div>}</div></section><aside className="summary"><h3>Order summary</h3><p><b>{product}</b><br/>{area}</p>{requestEnhancement&&<p className="badge">Image enhancement requested</p>}<p>Exact placement is saved as shown. We do not auto-center or resize.</p><hr style={{borderColor:'var(--line)'}}/><p><b>Print size</b><br/>Width: up to 11&quot;<br/>Height: up to 17&quot;</p><label><input type="checkbox"/> I checked spelling and placement.</label><br/><br/><label><input type="checkbox"/> I understand custom orders are final.</label><button className="glowbtn" style={{width:'100%',marginTop:18}}>Review & Checkout</button></aside></div></main></div>}
