'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {PublicNav} from '@/components/public-nav';
import {useLanguage} from '@/providers/language-provider';
import {getStudioT} from './lib/translations';
import {getProduct,products,type PrintArea,type ProductGroup} from './data/products';
import {ColorSelector} from './components/color-selector';
import {Preview} from './components/preview';
type D={image?:string;text?:string};
const empty:Record<PrintArea,D>={front:{},back:{},leftSleeve:{},rightSleeve:{},hood:{},pocket:{}};
export default function Studio(){const {language}=useLanguage();const t=getStudioT(language);const file=useRef<HTMLInputElement>(null);const[group,setGroup]=useState<ProductGroup>('adult');const[productId,setProductId]=useState('adult-tshirt');const[area,setArea]=useState<PrintArea>('front');const[colorId,setColorId]=useState('black');const[size,setSize]=useState('M');const[designs,setDesigns]=useState(empty);const[low,setLow]=useState(false);const[request,setRequest]=useState(false);const[saved,setSaved]=useState(false);const product=getProduct(productId);const color=product.colors.find(c=>c.id===colorId)??product.colors[0];const groupProducts=useMemo(()=>products.filter(p=>p.group===group),[group]);const labels:Record<PrintArea,string>={front:t.front,back:t.back,leftSleeve:t.leftSleeve,rightSleeve:t.rightSleeve,hood:t.hood,pocket:t.pocket};
useEffect(()=>{const raw=localStorage.getItem('ct-studio-v2');if(!raw)return;try{const d=JSON.parse(raw);setGroup(d.group??'adult');setProductId(d.productId??'adult-tshirt');setArea(d.area??'front');setColorId(d.colorId??'black');setSize(d.size??'M');setDesigns(d.designs??empty);setRequest(!!d.request)}catch{}},[]);
useEffect(()=>{const x=setTimeout(()=>{localStorage.setItem('ct-studio-v2',JSON.stringify({group,productId,area,colorId,size,designs,request}));setSaved(true);setTimeout(()=>setSaved(false),900)},500);return()=>clearTimeout(x)},[group,productId,area,colorId,size,designs,request]);
function switchGroup(g:ProductGroup){setGroup(g);const p=products.find(x=>x.group===g)??products[0];setProductId(p.id);setArea(p.areas[0]);setColorId(p.colors[0].id);setSize(p.sizes[0])}
function switchProduct(id:string){const p=getProduct(id);setProductId(id);setArea(p.areas[0]);setColorId(p.colors[0].id);setSize(p.sizes[0])}
function update(next:D){setDesigns(v=>({...v,[area]:{...v[area],...next}}))}
function upload(f?:File){if(!f)return;const u=URL.createObjectURL(f);update({image:u});const im=new Image();im.onload=()=>setLow(im.naturalWidth<900||im.naturalHeight<900);im.src=u}
function rotate(){const i=product.areas.indexOf(area);setArea(product.areas[(i+1)%product.areas.length])}
return <div className="shell"><PublicNav/><main className="container section"><div className="top"><div><h1 style={{fontSize:52,letterSpacing:-2,margin:0}}>{t.title}</h1><p className="muted">{t.sub}</p></div><span className="badge">{saved?t.saved:t.autosave}</span></div><div className="designer"><aside className="toolbox"><h3>Type</h3><div className="tabs">{(['adult','kids','bring-your-own'] as ProductGroup[]).map(g=><button key={g} className={'tab '+(group===g?'active':'')} onClick={()=>switchGroup(g)}>{g==='adult'?t.adult:g==='kids'?t.kids:t.byo}</button>)}</div><h3>{t.product}</h3><select value={productId} onChange={e=>switchProduct(e.target.value)}>{groupProducts.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><h3>{t.size}</h3><select value={size} onChange={e=>setSize(e.target.value)}>{product.sizes.map(s=><option key={s}>{s}</option>)}</select><ColorSelector colors={product.colors} selected={color.id} onChange={c=>setColorId(c.id)} label={t.color}/><h3>{t.area}</h3><div className="tabs">{product.areas.map(a=><button key={a} className={'tab '+(area===a?'active':'')} onClick={()=>setArea(a)}>{labels[a]}</button>)}</div><h3>{t.image}</h3><input ref={file} hidden type="file" accept="image/*" onChange={e=>upload(e.target.files?.[0])}/><button className="secondary" onClick={()=>file.current?.click()}>{designs[area].image?t.replace:t.upload}</button><h3>{t.text}</h3><textarea value={designs[area].text??''} placeholder={t.placeholder} onChange={e=>update({text:e.target.value})}/>{low&&<div className="warning"><b>{t.low}</b><br/>{t.lowBody}<label className="studioCheckRow"><input type="checkbox" checked={request} onChange={e=>setRequest(e.target.checked)}/><span>{t.request}</span></label></div>}</aside><Preview product={product} color={color} area={area} image={designs[area].image} text={designs[area].text} onRotate={rotate} rotateLabel={t.rotate}/><aside className="summary"><h3>{t.summary}</h3><p><b>{product.name}</b><br/>{color.name}<br/>{size}<br/>{labels[area]}</p>{request&&<p className="badge">{t.request}</p>}<p>{t.exact}</p><label className="studioCheckRow"><input type="checkbox"/><span>{t.checked}</span></label><label className="studioCheckRow"><input type="checkbox"/><span>{t.final}</span></label><button className="glowbtn" style={{width:'100%',marginTop:18}}>{t.checkout}</button></aside></div></main></div>}

